# workflow/.github/workflows/build-and-push-docker-image.yaml

name: Build and Push Docker Image

on:
  workflow_call:
    inputs:
      directory:
        description: 'The directory containing the Dockerfile'
        required: true
        type: string
      image_name:
        description: 'The Docker image name'
        required: true
        type: string
      tag:
        description: 'The Docker image tag'
        required: true
        type: string
      runner_debug:
        description: 'Enable runner debug logging'
        required: false
        type: boolean
        default: false
      step_debug:
        description: 'Enable step debug logging'
        required: false
        type: boolean
        default: false
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Enable Debug Logging
      if: ${{ inputs.runner_debug }}
      run: echo "ACTIONS_RUNNER_DEBUG=true" >> $GITHUB_ENV

    - name: Enable Step Debug Logging
      if: ${{ inputs.step_debug }}
      run: echo "ACTIONS_STEP_DEBUG=true" >> $GITHUB_ENV

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: all

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.image_name }}':'${{ inputs.tag }}

    - name: Create Buildx builder
      run: |
        docker buildx create --name mybuilder --use
        docker buildx inspect --bootstrap

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: ${{ inputs.directory }}
        file: ${{ inputs.directory }}/Dockerfile
        push: true
        provenance: mode=max
        sbom: true
        tags: ${{ secrets.DOCKER_USERNAME }}/${{ inputs.image_name }}:${{ inputs.tag }}
        platforms: linux/amd64,linux/arm64/v8
        cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/${{ inputs.image_name }}:cache
        cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/${{ inputs.image_name }}:cache,mode=max


    - name: Verify Built Images
      run: docker images